import { Character } from "@/types/Character";

// ============================================================================
// MOCK DATA — fallback cuando la API de Rick & Morty no está disponible
// Se activa automáticamente si la API falla (SSL expirado, timeout, etc.)
// ============================================================================

const BASE_IMG = "https://rickandmortyapi.com/api/character/avatar";
const BASE_EP = "https://rickandmortyapi.com/api/episode";

export const MOCK_CHARACTERS: Character[] = [
  {
    id: 1,
    name: "Rick Sanchez",
    species: "Human",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/1.jpeg`,
    origin: {
      name: "Earth (C-137)",
      url: "https://rickandmortyapi.com/api/location/1",
    },
    location: {
      name: "Citadel of Ricks",
      url: "https://rickandmortyapi.com/api/location/3",
    },
    episode: [`${BASE_EP}/1`, `${BASE_EP}/2`, `${BASE_EP}/3`],
  },
  {
    id: 2,
    name: "Morty Smith",
    species: "Human",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/2.jpeg`,
    origin: { name: "unknown", url: "" },
    location: {
      name: "Citadel of Ricks",
      url: "https://rickandmortyapi.com/api/location/3",
    },
    episode: [`${BASE_EP}/1`, `${BASE_EP}/2`, `${BASE_EP}/3`],
  },
  {
    id: 3,
    name: "Summer Smith",
    species: "Human",
    status: "Alive",
    gender: "Female",
    image: `${BASE_IMG}/3.jpeg`,
    origin: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    location: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    episode: [`${BASE_EP}/6`, `${BASE_EP}/7`, `${BASE_EP}/8`],
  },
  {
    id: 4,
    name: "Beth Smith",
    species: "Human",
    status: "Alive",
    gender: "Female",
    image: `${BASE_IMG}/4.jpeg`,
    origin: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    location: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    episode: [`${BASE_EP}/6`, `${BASE_EP}/7`, `${BASE_EP}/10`],
  },
  {
    id: 5,
    name: "Jerry Smith",
    species: "Human",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/5.jpeg`,
    origin: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    location: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    episode: [`${BASE_EP}/6`, `${BASE_EP}/7`, `${BASE_EP}/10`],
  },
  {
    id: 7,
    name: "Abradolf Lincler",
    species: "Human",
    status: "unknown",
    gender: "Male",
    image: `${BASE_IMG}/7.jpeg`,
    origin: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    location: {
      name: "Testicle Monster Dimension",
      url: "https://rickandmortyapi.com/api/location/21",
    },
    episode: [`${BASE_EP}/4`, `${BASE_EP}/5`],
  },
  {
    id: 17,
    name: "Annie",
    species: "Human",
    status: "Alive",
    gender: "Female",
    image: `${BASE_IMG}/17.jpeg`,
    origin: { name: "unknown", url: "" },
    location: {
      name: "Anatomy Park",
      url: "https://rickandmortyapi.com/api/location/5",
    },
    episode: [`${BASE_EP}/3`],
  },
  {
    id: 18,
    name: "Antenna Morty",
    species: "Human",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/18.jpeg`,
    origin: { name: "unknown", url: "" },
    location: {
      name: "Citadel of Ricks",
      url: "https://rickandmortyapi.com/api/location/3",
    },
    episode: [`${BASE_EP}/10`, `${BASE_EP}/28`],
  },
  {
    id: 19,
    name: "Antenna Rick",
    species: "Human",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/19.jpeg`,
    origin: { name: "unknown", url: "" },
    location: {
      name: "Citadel of Ricks",
      url: "https://rickandmortyapi.com/api/location/3",
    },
    episode: [`${BASE_EP}/10`],
  },
  {
    id: 22,
    name: "Armagheadon",
    species: "Alien",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/22.jpeg`,
    origin: { name: "unknown", url: "" },
    location: { name: "unknown", url: "" },
    episode: [`${BASE_EP}/4`],
  },
  {
    id: 23,
    name: "Armothy",
    species: "unknown",
    status: "Dead",
    gender: "Male",
    image: `${BASE_IMG}/23.jpeg`,
    origin: {
      name: "Post-Apocalyptic Earth",
      url: "https://rickandmortyapi.com/api/location/8",
    },
    location: {
      name: "Post-Apocalyptic Earth",
      url: "https://rickandmortyapi.com/api/location/8",
    },
    episode: [`${BASE_EP}/23`],
  },
  {
    id: 24,
    name: "Arthricia",
    species: "Alien",
    status: "Alive",
    gender: "Female",
    image: `${BASE_IMG}/24.jpeg`,
    origin: {
      name: "Purge Planet",
      url: "https://rickandmortyapi.com/api/location/9",
    },
    location: {
      name: "Purge Planet",
      url: "https://rickandmortyapi.com/api/location/9",
    },
    episode: [`${BASE_EP}/9`],
  },
  {
    id: 25,
    name: "Baby Legs",
    species: "Human",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/25.jpeg`,
    origin: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    location: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    episode: [`${BASE_EP}/8`],
  },
  {
    id: 27,
    name: "Bepisian",
    species: "Alien",
    status: "Alive",
    gender: "unknown",
    image: `${BASE_IMG}/27.jpeg`,
    origin: { name: "Bepis 9", url: "" },
    location: { name: "Bepis 9", url: "" },
    episode: [`${BASE_EP}/7`],
  },
  {
    id: 29,
    name: "Big Morty",
    species: "Human",
    status: "Dead",
    gender: "Male",
    image: `${BASE_IMG}/29.jpeg`,
    origin: { name: "unknown", url: "" },
    location: {
      name: "Citadel of Ricks",
      url: "https://rickandmortyapi.com/api/location/3",
    },
    episode: [`${BASE_EP}/10`],
  },
  {
    id: 30,
    name: "Bird Person",
    species: "Alien",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/30.jpeg`,
    origin: { name: "Bird World", url: "" },
    location: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    episode: [`${BASE_EP}/8`, `${BASE_EP}/18`],
  },
  {
    id: 32,
    name: "Blim Blam",
    species: "Alien",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/32.jpeg`,
    origin: { name: "Kalaxian Crystal Planet", url: "" },
    location: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    episode: [`${BASE_EP}/12`],
  },
  {
    id: 33,
    name: "Body Guard Morty",
    species: "Human",
    status: "Dead",
    gender: "Male",
    image: `${BASE_IMG}/33.jpeg`,
    origin: { name: "unknown", url: "" },
    location: {
      name: "Citadel of Ricks",
      url: "https://rickandmortyapi.com/api/location/3",
    },
    episode: [`${BASE_EP}/10`],
  },
  {
    id: 34,
    name: "Bojo",
    species: "Alien",
    status: "Dead",
    gender: "Male",
    image: `${BASE_IMG}/34.jpeg`,
    origin: { name: "unknown", url: "" },
    location: { name: "Interdimensional Customs", url: "" },
    episode: [`${BASE_EP}/2`],
  },
  {
    id: 35,
    name: "Borderlands Rick",
    species: "Human",
    status: "unknown",
    gender: "Male",
    image: `${BASE_IMG}/35.jpeg`,
    origin: { name: "unknown", url: "" },
    location: {
      name: "Citadel of Ricks",
      url: "https://rickandmortyapi.com/api/location/3",
    },
    episode: [`${BASE_EP}/10`],
  },
  // Page 2 characters
  {
    id: 36,
    name: "Boss",
    species: "Human",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/36.jpeg`,
    origin: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    location: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    episode: [`${BASE_EP}/8`],
  },
  {
    id: 37,
    name: "Brad Anderson",
    species: "Human",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/37.jpeg`,
    origin: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    location: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    episode: [`${BASE_EP}/11`],
  },
  {
    id: 38,
    name: "Brenda",
    species: "Human",
    status: "Dead",
    gender: "Female",
    image: `${BASE_IMG}/38.jpeg`,
    origin: { name: "unknown", url: "" },
    location: { name: "unknown", url: "" },
    episode: [`${BASE_EP}/11`],
  },
  {
    id: 40,
    name: "Butter Robot",
    species: "Robot",
    status: "Alive",
    gender: "unknown",
    image: `${BASE_IMG}/40.jpeg`,
    origin: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    location: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    episode: [`${BASE_EP}/9`],
  },
  {
    id: 41,
    name: "Buttoneer",
    species: "Alien",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/41.jpeg`,
    origin: { name: "unknown", url: "" },
    location: { name: "unknown", url: "" },
    episode: [`${BASE_EP}/6`],
  },
  {
    id: 44,
    name: "CEO of Apple",
    species: "Human",
    status: "Dead",
    gender: "Male",
    image: `${BASE_IMG}/44.jpeg`,
    origin: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    location: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    episode: [`${BASE_EP}/4`],
  },
  {
    id: 45,
    name: "Ceramic Chicken",
    species: "unknown",
    status: "Alive",
    gender: "unknown",
    image: `${BASE_IMG}/45.jpeg`,
    origin: { name: "unknown", url: "" },
    location: { name: "unknown", url: "" },
    episode: [`${BASE_EP}/8`],
  },
  {
    id: 46,
    name: "Champion Rick",
    species: "Human",
    status: "unknown",
    gender: "Male",
    image: `${BASE_IMG}/46.jpeg`,
    origin: { name: "unknown", url: "" },
    location: {
      name: "Citadel of Ricks",
      url: "https://rickandmortyapi.com/api/location/3",
    },
    episode: [`${BASE_EP}/10`],
  },
  {
    id: 47,
    name: "Changeling",
    species: "Alien",
    status: "Alive",
    gender: "unknown",
    image: `${BASE_IMG}/47.jpeg`,
    origin: { name: "unknown", url: "" },
    location: { name: "unknown", url: "" },
    episode: [`${BASE_EP}/7`],
  },
  {
    id: 48,
    name: "Charlie",
    species: "Human",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/48.jpeg`,
    origin: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    location: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    episode: [`${BASE_EP}/11`],
  },
  {
    id: 49,
    name: "Chris",
    species: "Human",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/49.jpeg`,
    origin: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    location: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    episode: [`${BASE_EP}/11`],
  },
  // Page 3 characters
  {
    id: 50,
    name: "Coach Feratu",
    species: "Humanoid",
    status: "Dead",
    gender: "Male",
    image: `${BASE_IMG}/50.jpeg`,
    origin: { name: "unknown", url: "" },
    location: { name: "unknown", url: "" },
    episode: [`${BASE_EP}/23`],
  },
  {
    id: 51,
    name: "Concerto",
    species: "Alien",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/51.jpeg`,
    origin: { name: "Girvonesk", url: "" },
    location: { name: "Girvonesk", url: "" },
    episode: [`${BASE_EP}/22`],
  },
  {
    id: 57,
    name: "Cool Rick",
    species: "Human",
    status: "Dead",
    gender: "Male",
    image: `${BASE_IMG}/57.jpeg`,
    origin: { name: "unknown", url: "" },
    location: {
      name: "Citadel of Ricks",
      url: "https://rickandmortyapi.com/api/location/3",
    },
    episode: [`${BASE_EP}/10`],
  },
  {
    id: 58,
    name: "Cop Morty",
    species: "Human",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/58.jpeg`,
    origin: { name: "unknown", url: "" },
    location: {
      name: "Citadel of Ricks",
      url: "https://rickandmortyapi.com/api/location/3",
    },
    episode: [`${BASE_EP}/10`],
  },
  {
    id: 60,
    name: "Craig",
    species: "Human",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/60.jpeg`,
    origin: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    location: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    episode: [`${BASE_EP}/20`],
  },
  {
    id: 61,
    name: "Crystal Bith Morty",
    species: "Human",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/61.jpeg`,
    origin: { name: "unknown", url: "" },
    location: {
      name: "Citadel of Ricks",
      url: "https://rickandmortyapi.com/api/location/3",
    },
    episode: [`${BASE_EP}/10`],
  },
  {
    id: 62,
    name: "Crystal Pooper",
    species: "Alien",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/62.jpeg`,
    origin: { name: "unknown", url: "" },
    location: { name: "unknown", url: "" },
    episode: [`${BASE_EP}/28`],
  },
  {
    id: 63,
    name: "Davin",
    species: "Human",
    status: "Alive",
    gender: "Male",
    image: `${BASE_IMG}/63.jpeg`,
    origin: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    location: {
      name: "Earth (Replacement Dimension)",
      url: "https://rickandmortyapi.com/api/location/20",
    },
    episode: [`${BASE_EP}/8`],
  },
  {
    id: 64,
    name: "Dead Cat",
    species: "Animal",
    status: "Dead",
    gender: "unknown",
    image: `${BASE_IMG}/64.jpeg`,
    origin: { name: "unknown", url: "" },
    location: { name: "unknown", url: "" },
    episode: [`${BASE_EP}/20`],
  },
  {
    id: 65,
    name: "Dead Presidents Morty",
    species: "Human",
    status: "Dead",
    gender: "Male",
    image: `${BASE_IMG}/65.jpeg`,
    origin: { name: "unknown", url: "" },
    location: {
      name: "Citadel of Ricks",
      url: "https://rickandmortyapi.com/api/location/3",
    },
    episode: [`${BASE_EP}/10`],
  },
];

export interface MockEpisodeResponse {
  id: number;
  name: string;
  air_date: string;
  episode: string;
  characters: string[];
  url: string;
  created: string;
}

const BASE_CHAR = "https://rickandmortyapi.com/api/character";

export const MOCK_EPISODES: MockEpisodeResponse[] = [
  {
    id: 1,
    name: "Pilot",
    air_date: "December 2, 2013",
    episode: "S01E01",
    characters: [
      `${BASE_CHAR}/1`,
      `${BASE_CHAR}/2`,
      `${BASE_CHAR}/35`,
      `${BASE_CHAR}/38`,
      `${BASE_CHAR}/62`,
      `${BASE_CHAR}/92`,
      `${BASE_CHAR}/127`,
      `${BASE_CHAR}/144`,
      `${BASE_CHAR}/158`,
      `${BASE_CHAR}/175`,
      `${BASE_CHAR}/179`,
      `${BASE_CHAR}/181`,
      `${BASE_CHAR}/239`,
      `${BASE_CHAR}/249`,
      `${BASE_CHAR}/271`,
      `${BASE_CHAR}/338`,
      `${BASE_CHAR}/394`,
      `${BASE_CHAR}/395`,
      `${BASE_CHAR}/435`,
    ],
    url: `${BASE_EP}/1`,
    created: "2017-11-10T12:56:33.798Z",
  },
  {
    id: 2,
    name: "Lawnmower Dog",
    air_date: "December 9, 2013",
    episode: "S01E02",
    characters: [
      `${BASE_CHAR}/1`,
      `${BASE_CHAR}/2`,
      `${BASE_CHAR}/3`,
      `${BASE_CHAR}/4`,
      `${BASE_CHAR}/5`,
      `${BASE_CHAR}/34`,
    ],
    url: `${BASE_EP}/2`,
    created: "2017-11-10T12:56:33.916Z",
  },
  {
    id: 3,
    name: "Anatomy Park",
    air_date: "December 16, 2013",
    episode: "S01E03",
    characters: [
      `${BASE_CHAR}/1`,
      `${BASE_CHAR}/2`,
      `${BASE_CHAR}/3`,
      `${BASE_CHAR}/4`,
      `${BASE_CHAR}/5`,
      `${BASE_CHAR}/17`,
    ],
    url: `${BASE_EP}/3`,
    created: "2017-11-10T12:56:34.022Z",
  },
  {
    id: 4,
    name: "M. Night Shaym-Aliens!",
    air_date: "January 13, 2014",
    episode: "S01E04",
    characters: [
      `${BASE_CHAR}/1`,
      `${BASE_CHAR}/2`,
      `${BASE_CHAR}/7`,
      `${BASE_CHAR}/22`,
      `${BASE_CHAR}/44`,
    ],
    url: `${BASE_EP}/4`,
    created: "2017-11-10T12:56:34.129Z",
  },
  {
    id: 5,
    name: "Meeseeks and Destroy",
    air_date: "January 20, 2014",
    episode: "S01E05",
    characters: [
      `${BASE_CHAR}/1`,
      `${BASE_CHAR}/2`,
      `${BASE_CHAR}/3`,
      `${BASE_CHAR}/4`,
      `${BASE_CHAR}/5`,
      `${BASE_CHAR}/7`,
    ],
    url: `${BASE_EP}/5`,
    created: "2017-11-10T12:56:34.236Z",
  },
  {
    id: 6,
    name: "Rick Potion #9",
    air_date: "January 27, 2014",
    episode: "S01E06",
    characters: [
      `${BASE_CHAR}/1`,
      `${BASE_CHAR}/2`,
      `${BASE_CHAR}/3`,
      `${BASE_CHAR}/4`,
      `${BASE_CHAR}/5`,
      `${BASE_CHAR}/41`,
    ],
    url: `${BASE_EP}/6`,
    created: "2017-11-10T12:56:34.337Z",
  },
  {
    id: 7,
    name: "Raising Gazorpazorp",
    air_date: "March 10, 2014",
    episode: "S01E07",
    characters: [
      `${BASE_CHAR}/1`,
      `${BASE_CHAR}/2`,
      `${BASE_CHAR}/3`,
      `${BASE_CHAR}/27`,
      `${BASE_CHAR}/47`,
    ],
    url: `${BASE_EP}/7`,
    created: "2017-11-10T12:56:34.431Z",
  },
  {
    id: 8,
    name: "Rixty Minutes",
    air_date: "March 17, 2014",
    episode: "S01E08",
    characters: [
      `${BASE_CHAR}/1`,
      `${BASE_CHAR}/2`,
      `${BASE_CHAR}/3`,
      `${BASE_CHAR}/4`,
      `${BASE_CHAR}/5`,
      `${BASE_CHAR}/25`,
      `${BASE_CHAR}/30`,
      `${BASE_CHAR}/36`,
      `${BASE_CHAR}/63`,
    ],
    url: `${BASE_EP}/8`,
    created: "2017-11-10T12:56:34.524Z",
  },
  {
    id: 9,
    name: "Something Ricked This Way Comes",
    air_date: "March 24, 2014",
    episode: "S01E09",
    characters: [
      `${BASE_CHAR}/1`,
      `${BASE_CHAR}/2`,
      `${BASE_CHAR}/3`,
      `${BASE_CHAR}/4`,
      `${BASE_CHAR}/5`,
      `${BASE_CHAR}/24`,
      `${BASE_CHAR}/40`,
    ],
    url: `${BASE_EP}/9`,
    created: "2017-11-10T12:56:34.619Z",
  },
  {
    id: 10,
    name: "Close Rick-counters of the Rick Kind",
    air_date: "April 7, 2014",
    episode: "S01E10",
    characters: [
      `${BASE_CHAR}/1`,
      `${BASE_CHAR}/2`,
      `${BASE_CHAR}/18`,
      `${BASE_CHAR}/19`,
      `${BASE_CHAR}/29`,
      `${BASE_CHAR}/30`,
      `${BASE_CHAR}/33`,
      `${BASE_CHAR}/35`,
      `${BASE_CHAR}/46`,
      `${BASE_CHAR}/57`,
      `${BASE_CHAR}/58`,
      `${BASE_CHAR}/61`,
      `${BASE_CHAR}/65`,
    ],
    url: `${BASE_EP}/10`,
    created: "2017-11-10T12:56:34.700Z",
  },
  {
    id: 11,
    name: "Ricksy Business",
    air_date: "April 14, 2014",
    episode: "S01E11",
    characters: [
      `${BASE_CHAR}/1`,
      `${BASE_CHAR}/2`,
      `${BASE_CHAR}/3`,
      `${BASE_CHAR}/4`,
      `${BASE_CHAR}/5`,
      `${BASE_CHAR}/37`,
      `${BASE_CHAR}/38`,
      `${BASE_CHAR}/48`,
      `${BASE_CHAR}/49`,
    ],
    url: `${BASE_EP}/11`,
    created: "2017-11-10T12:56:34.793Z",
  },
  {
    id: 12,
    name: "A Rickle in Time",
    air_date: "July 26, 2015",
    episode: "S02E01",
    characters: [
      `${BASE_CHAR}/1`,
      `${BASE_CHAR}/2`,
      `${BASE_CHAR}/3`,
      `${BASE_CHAR}/4`,
      `${BASE_CHAR}/5`,
      `${BASE_CHAR}/32`,
    ],
    url: `${BASE_EP}/12`,
    created: "2017-11-10T12:56:34.883Z",
  },
];
